plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.testng:testng:7.11.0'
    implementation 'io.appium:java-client:9.2.2'
}

test {
    useTestNG()
}

def registerTask(String taskName, String suitePath) {
    tasks.register(taskName,Test) {
        useTestNG() {
            suites suitePath
        }
        if (project.hasProperty('browser')) {
            systemProperty 'browser', "${browser}"
        }
    }
}

registerTask('regression','src/test/resources/smoky.xml')
